package com.exacttarget.wsdl.partnerapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * ExactTarget Partner API
 *
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T10:01:53.231+10:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "PartnerAPI", 
                  wsdlLocation = "https://webservice.s7.exacttarget.com/etframework.wsdl",
                  targetNamespace = "http://exacttarget.com/wsdl/partnerAPI") 
public class PartnerAPI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://exacttarget.com/wsdl/partnerAPI", "PartnerAPI");
    public final static QName Soap = new QName("http://exacttarget.com/wsdl/partnerAPI", "Soap");
    static {
        URL url = null;
        try {
            url = new URL("https://webservice.s7.exacttarget.com/etframework.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PartnerAPI.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://webservice.s7.exacttarget.com/etframework.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PartnerAPI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PartnerAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerAPI() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PartnerAPI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PartnerAPI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PartnerAPI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap() {
        return super.getPort(Soap, Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap(WebServiceFeature... features) {
        return super.getPort(Soap, Soap.class, features);
    }

}
