package com.exacttarget.wsdl.partnerapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T10:01:53.192+10:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", name = "Soap")
@XmlSeeAlso({com.exacttarget.partner.fault.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Soap {

    @WebResult(name = "PerformResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Perform", action = "Perform")
    public PerformResponseMsg perform(
        @WebParam(partName = "parameters", name = "PerformRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        PerformRequestMsg parameters
    );

    /**
     * Perform ad hoc data extracts
     */
    @WebResult(name = "ExtractResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Extract", action = "Extract")
    public ExtractResponseMsg extract(
        @WebParam(partName = "parameters", name = "ExtractRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        ExtractRequestMsg parameters
    );

    @WebResult(name = "QueryResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Query", action = "Query")
    public QueryResponseMsg query(
        @WebParam(partName = "parameters", name = "QueryRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        QueryRequestMsg parameters
    );

    /**
     * Retrieve objects
     */
    @WebResult(name = "RetrieveResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Retrieve", action = "Retrieve")
    public RetrieveResponseMsg retrieve(
        @WebParam(partName = "parameters", name = "RetrieveRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        RetrieveRequestMsg parameters
    );

    @WebResult(name = "ExecuteResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Execute", action = "Execute")
    public ExecuteResponseMsg execute(
        @WebParam(partName = "parameters", name = "ExecuteRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        ExecuteRequestMsg parameters
    );

    @WebResult(name = "ConfigureResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Configure", action = "Configure")
    public ConfigureResponseMsg configure(
        @WebParam(partName = "parameters", name = "ConfigureRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        ConfigureRequestMsg parameters
    );

    /**
     * Get Current System Status
     */
    @WebResult(name = "SystemStatusResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "GetSystemStatus", action = "GetSystemStatus")
    public SystemStatusResponseMsg getSystemStatus(
        @WebParam(partName = "parameters", name = "SystemStatusRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        SystemStatusRequestMsg parameters
    );

    @WebResult(name = "DefinitionResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Describe", action = "Describe")
    public DefinitionResponseMsg describe(
        @WebParam(partName = "parameters", name = "DefinitionRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        DefinitionRequestMsg parameters
    );

    /**
     * Update objects
     */
    @WebResult(name = "UpdateResponse", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Update", action = "Update")
    public UpdateResponse update(
        @WebParam(partName = "parameters", name = "UpdateRequest", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        UpdateRequest parameters
    );

    @WebResult(name = "ScheduleResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Schedule", action = "Schedule")
    public ScheduleResponseMsg schedule(
        @WebParam(partName = "parameters", name = "ScheduleRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        ScheduleRequestMsg parameters
    );

    /**
     * Delete objects
     */
    @WebResult(name = "DeleteResponse", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Delete", action = "Delete")
    public DeleteResponse delete(
        @WebParam(partName = "parameters", name = "DeleteRequest", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        DeleteRequest parameters
    );

    @WebResult(name = "VersionInfoResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "VersionInfo", action = "VersionInfo")
    public VersionInfoResponseMsg versionInfo(
        @WebParam(partName = "parameters", name = "VersionInfoRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        VersionInfoRequestMsg parameters
    );

    /**
     * Create objects
     */
    @WebResult(name = "CreateResponse", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    @WebMethod(operationName = "Create", action = "Create")
    public CreateResponse create(
        @WebParam(partName = "parameters", name = "CreateRequest", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
        CreateRequest parameters
    );
}
